-- Import Rachel's 7/31-8/10 Santa Clara schedule as real data.
begin;
-- 52 staff
insert into sched_staff (name, home_hall, active) values
  ('Alex', 'sc', true),
  ('Alonso', 'sc', true),
  ('Amanda', 'sc', true),
  ('Andrea', 'sc', true),
  ('Cameron', 'sc', true),
  ('Cindy', 'sc', true),
  ('Claudia', 'sc', true),
  ('Cody', 'sc', true),
  ('Dante', 'sc', true),
  ('Elena', 'sc', true),
  ('Esteban', 'sc', true),
  ('Esther', 'sc', true),
  ('Ethan', 'sc', true),
  ('Gaby', 'sc', true),
  ('Gina', 'sc', true),
  ('Giovanna', 'sc', true),
  ('Hector', 'sc', true),
  ('Ian', 'sc', true),
  ('Iraina', 'sc', true),
  ('JD', 'sc', true),
  ('James C.', 'sc', true),
  ('James G.', 'sc', true),
  ('Jordy', 'sc', true),
  ('Jose', 'sc', true),
  ('Justin', 'sc', true),
  ('Katie', 'sc', true),
  ('Kaylyn', 'sc', true),
  ('Kristen', 'sc', true),
  ('Malaya', 'sc', true),
  ('Michael L.', 'sc', true),
  ('Michael S.', 'sc', true),
  ('Nancy', 'sc', true),
  ('Nate', 'sc', true),
  ('Nathan', 'sc', true),
  ('Osbaldo', 'sc', true),
  ('Paolo', 'sc', true),
  ('Paula', 'sc', true),
  ('Rachel', 'sc', true),
  ('Raman', 'sc', true),
  ('Ruthie', 'sc', true),
  ('Sagit', 'sc', true),
  ('Sammy', 'sc', true),
  ('Sarah', 'sc', true),
  ('Sergiy', 'sc', true),
  ('Shelly', 'sc', true),
  ('Tatiana', 'sc', true),
  ('Thao', 'sc', true),
  ('Tibet', 'sc', true),
  ('Tiffany', 'sc', true),
  ('Tim', 'sc', true),
  ('Virginia', 'sc', true),
  ('Wayne', 'sc', true)
on conflict do nothing;

insert into sched_sessions (hall_id, session_date, part, day_type, status, published_at) values ('sc', '2026-07-31', 'single', 'weekday', 'deployed', now()) on conflict (hall_id, session_date, part) do nothing;
insert into sched_sessions (hall_id, session_date, part, day_type, status, published_at) values ('sc', '2026-08-01', 'AM', 'weekend', 'deployed', now()) on conflict (hall_id, session_date, part) do nothing;
insert into sched_sessions (hall_id, session_date, part, day_type, status, published_at) values ('sc', '2026-08-01', 'PM', 'weekend', 'deployed', now()) on conflict (hall_id, session_date, part) do nothing;
insert into sched_sessions (hall_id, session_date, part, day_type, status, published_at) values ('sc', '2026-08-02', 'AM', 'weekend', 'deployed', now()) on conflict (hall_id, session_date, part) do nothing;
insert into sched_sessions (hall_id, session_date, part, day_type, status, published_at) values ('sc', '2026-08-02', 'PM', 'weekend', 'deployed', now()) on conflict (hall_id, session_date, part) do nothing;
insert into sched_sessions (hall_id, session_date, part, day_type, status, published_at) values ('sc', '2026-08-03', 'single', 'weekday', 'deployed', now()) on conflict (hall_id, session_date, part) do nothing;
insert into sched_sessions (hall_id, session_date, part, day_type, status, published_at) values ('sc', '2026-08-07', 'single', 'weekday', 'deployed', now()) on conflict (hall_id, session_date, part) do nothing;
insert into sched_sessions (hall_id, session_date, part, day_type, status, published_at) values ('sc', '2026-08-08', 'AM', 'weekend', 'deployed', now()) on conflict (hall_id, session_date, part) do nothing;
insert into sched_sessions (hall_id, session_date, part, day_type, status, published_at) values ('sc', '2026-08-08', 'PM', 'weekend', 'deployed', now()) on conflict (hall_id, session_date, part) do nothing;
insert into sched_sessions (hall_id, session_date, part, day_type, status, published_at) values ('sc', '2026-08-09', 'AM', 'weekend', 'deployed', now()) on conflict (hall_id, session_date, part) do nothing;
insert into sched_sessions (hall_id, session_date, part, day_type, status, published_at) values ('sc', '2026-08-09', 'PM', 'weekend', 'deployed', now()) on conflict (hall_id, session_date, part) do nothing;
insert into sched_sessions (hall_id, session_date, part, day_type, status, published_at) values ('sc', '2026-08-10', 'single', 'weekday', 'deployed', now()) on conflict (hall_id, session_date, part) do nothing;

-- assignments
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-07-31' and ss.part='single' and r.name='MOD' and st.name='Gina' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-07-31' and ss.part='single' and r.name='Opener/Swing Shift' and st.name='Raman' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-07-31' and ss.part='single' and r.name='Paymaster' and st.name='James C.' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-07-31' and ss.part='single' and r.name='Flash Manager' and st.name='Shelly' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-07-31' and ss.part='single' and r.name='Callers/Strip' and st.name='Gina' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 1, true, false, 'Kaylyn*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-07-31' and ss.part='single' and r.name='Callers/Strip' and st.name='Kaylyn' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 2, true, false, 'Nathan*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-07-31' and ss.part='single' and r.name='Callers/Strip' and st.name='Nathan' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 3, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-07-31' and ss.part='single' and r.name='Callers/Strip' and st.name='Ruthie' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-07-31' and ss.part='single' and r.name='Flash Runners' and st.name='Esteban' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 1, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-07-31' and ss.part='single' and r.name='Flash Runners' and st.name='Gaby' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 2, true, false, 'Virginia*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-07-31' and ss.part='single' and r.name='Flash Runners' and st.name='Virginia' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 3, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-07-31' and ss.part='single' and r.name='Flash Runners' and st.name='Jose' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 4, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-07-31' and ss.part='single' and r.name='Flash Runners' and st.name='Cindy' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 5, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-07-31' and ss.part='single' and r.name='Flash Runners' and st.name='James G.' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 6, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-07-31' and ss.part='single' and r.name='Flash Runners' and st.name='Giovanna' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 7, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-07-31' and ss.part='single' and r.name='Flash Runners' and st.name='Elena' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 8, true, false, 'Kristen*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-07-31' and ss.part='single' and r.name='Flash Runners' and st.name='Kristen' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 9, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-07-31' and ss.part='single' and r.name='Flash Runners' and st.name='Michael S.' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 10, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-07-31' and ss.part='single' and r.name='Flash Runners' and st.name='Alonso' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 11, false, true, 'Thao-Training', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-07-31' and ss.part='single' and r.name='Flash Runners' and st.name='Thao' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='AM' and r.name='MOD' and st.name='Sagit' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='AM' and r.name='Opener/Swing Shift' and st.name='Sagit' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='AM' and r.name='Paymaster' and st.name='Nancy' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='AM' and r.name='Flash Manager' and st.name='Wayne' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='AM' and r.name='Callers/Strip' and st.name='Tatiana' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 1, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='AM' and r.name='Callers/Strip' and st.name='Esther' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 2, true, false, 'Nathan*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='AM' and r.name='Callers/Strip' and st.name='Nathan' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 3, true, false, 'Raman*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='AM' and r.name='Callers/Strip' and st.name='Raman' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='AM' and r.name='Flash Runners' and st.name='Tiffany' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 1, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='AM' and r.name='Flash Runners' and st.name='Hector' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 2, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='AM' and r.name='Flash Runners' and st.name='Tibet' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 3, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='AM' and r.name='Flash Runners' and st.name='Iraina' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 4, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='AM' and r.name='Flash Runners' and st.name='Cindy' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 5, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='AM' and r.name='Flash Runners' and st.name='James G.' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 6, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='AM' and r.name='Flash Runners' and st.name='Giovanna' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 7, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='AM' and r.name='Flash Runners' and st.name='Elena' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 8, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='AM' and r.name='Flash Runners' and st.name='Nate' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 9, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='AM' and r.name='Flash Runners' and st.name='Amanda' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 10, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='AM' and r.name='Flash Runners' and st.name='Katie' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 11, true, false, 'Sammy*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='AM' and r.name='Flash Runners' and st.name='Sammy' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='PM' and r.name='MOD' and st.name='Sagit' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='PM' and r.name='Opener/Swing Shift' and st.name='Sammy' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='PM' and r.name='Paymaster' and st.name='Esther' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='PM' and r.name='Flash Manager' and st.name='Kristen' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='PM' and r.name='Callers/Strip' and st.name='Tatiana' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 1, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='PM' and r.name='Callers/Strip' and st.name='Nathan' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 2, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='PM' and r.name='Callers/Strip' and st.name='James C.' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 3, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='PM' and r.name='Callers/Strip' and st.name='Raman' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='PM' and r.name='Flash Runners' and st.name='Osbaldo' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 1, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='PM' and r.name='Flash Runners' and st.name='Hector' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 2, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='PM' and r.name='Flash Runners' and st.name='Tibet' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 3, false, false, 'Sergiy (new)', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='PM' and r.name='Flash Runners' and st.name='Sergiy' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 4, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='PM' and r.name='Flash Runners' and st.name='Thao' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 5, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='PM' and r.name='Flash Runners' and st.name='Ian' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 6, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='PM' and r.name='Flash Runners' and st.name='Claudia' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 7, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='PM' and r.name='Flash Runners' and st.name='Elena' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 8, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='PM' and r.name='Flash Runners' and st.name='Iraina' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 9, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='PM' and r.name='Flash Runners' and st.name='Michael S.' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 10, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-01' and ss.part='PM' and r.name='Flash Runners' and st.name='Alonso' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='AM' and r.name='MOD' and st.name='Rachel' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='AM' and r.name='Opener/Swing Shift' and st.name='Rachel' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='AM' and r.name='Paymaster' and st.name='Nancy' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='AM' and r.name='Flash Manager' and st.name='Gina' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, true, false, 'Wayne*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='AM' and r.name='Callers/Strip' and st.name='Wayne' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 1, true, false, 'Kaylyn*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='AM' and r.name='Callers/Strip' and st.name='Kaylyn' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 2, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='AM' and r.name='Callers/Strip' and st.name='James C.' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 3, true, false, 'Raman*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='AM' and r.name='Callers/Strip' and st.name='Raman' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='AM' and r.name='Flash Runners' and st.name='Tiffany' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 1, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='AM' and r.name='Flash Runners' and st.name='Hector' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 2, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='AM' and r.name='Flash Runners' and st.name='Justin' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 3, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='AM' and r.name='Flash Runners' and st.name='Michael L.' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 4, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='AM' and r.name='Flash Runners' and st.name='Jordy' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 5, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='AM' and r.name='Flash Runners' and st.name='Ian' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 6, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='AM' and r.name='Flash Runners' and st.name='Malaya' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 7, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='AM' and r.name='Flash Runners' and st.name='Alonso' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 8, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='AM' and r.name='Flash Runners' and st.name='Amanda' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 9, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='AM' and r.name='Flash Runners' and st.name='Katie' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='PM' and r.name='MOD' and st.name='Rachel' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='PM' and r.name='Opener/Swing Shift' and st.name='Raman' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='PM' and r.name='Paymaster' and st.name='Wayne' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='PM' and r.name='Flash Manager' and st.name='Esther' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='PM' and r.name='Callers/Strip' and st.name='Tatiana' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 1, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='PM' and r.name='Callers/Strip' and st.name='Kaylyn' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 2, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='PM' and r.name='Callers/Strip' and st.name='James C.' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 3, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='PM' and r.name='Callers/Strip' and st.name='Paula' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='PM' and r.name='Flash Runners' and st.name='Osbaldo' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 1, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='PM' and r.name='Flash Runners' and st.name='Hector' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 2, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='PM' and r.name='Flash Runners' and st.name='Tibet' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 3, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='PM' and r.name='Flash Runners' and st.name='Sergiy' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 4, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='PM' and r.name='Flash Runners' and st.name='Thao' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 5, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='PM' and r.name='Flash Runners' and st.name='Alex' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 6, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='PM' and r.name='Flash Runners' and st.name='Claudia' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 7, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='PM' and r.name='Flash Runners' and st.name='Malaya' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 8, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='PM' and r.name='Flash Runners' and st.name='Nate' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 9, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-02' and ss.part='PM' and r.name='Flash Runners' and st.name='Dante' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, 'Sagit/Rachel', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-03' and ss.part='single' and r.name='MOD' and st.name='Sagit' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-03' and ss.part='single' and r.name='Opener/Swing Shift' and st.name='Wayne' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-03' and ss.part='single' and r.name='Paymaster' and st.name='Sagit' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-03' and ss.part='single' and r.name='Flash Manager' and st.name='Paolo' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-03' and ss.part='single' and r.name='Callers/Strip' and st.name='Gina' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 1, true, false, 'Wayne*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-03' and ss.part='single' and r.name='Callers/Strip' and st.name='Wayne' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 2, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-03' and ss.part='single' and r.name='Callers/Strip' and st.name='James C.' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 3, true, false, 'Ruthie/Raman*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-03' and ss.part='single' and r.name='Callers/Strip' and st.name='Ruthie' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-03' and ss.part='single' and r.name='Flash Runners' and st.name='Esteban' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 1, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-03' and ss.part='single' and r.name='Flash Runners' and st.name='Tim' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 2, true, false, 'Virginia*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-03' and ss.part='single' and r.name='Flash Runners' and st.name='Virginia' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 3, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-03' and ss.part='single' and r.name='Flash Runners' and st.name='Jose' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 4, true, false, 'Nathan*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-03' and ss.part='single' and r.name='Flash Runners' and st.name='Nathan' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 5, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-03' and ss.part='single' and r.name='Flash Runners' and st.name='James G.' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 6, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-03' and ss.part='single' and r.name='Flash Runners' and st.name='Claudia' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 7, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-03' and ss.part='single' and r.name='Flash Runners' and st.name='Malaya' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 8, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-03' and ss.part='single' and r.name='Flash Runners' and st.name='Andrea' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 9, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-03' and ss.part='single' and r.name='Flash Runners' and st.name='Tibet' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 10, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-03' and ss.part='single' and r.name='Flash Runners' and st.name='Dante' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-07' and ss.part='single' and r.name='MOD' and st.name='Gina' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-07' and ss.part='single' and r.name='Opener/Swing Shift' and st.name='Raman' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-07' and ss.part='single' and r.name='Paymaster' and st.name='James C.' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-07' and ss.part='single' and r.name='Flash Manager' and st.name='Paolo' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-07' and ss.part='single' and r.name='Callers/Strip' and st.name='Gina' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 1, true, false, 'Cody*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-07' and ss.part='single' and r.name='Callers/Strip' and st.name='Cody' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 2, true, false, 'JD*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-07' and ss.part='single' and r.name='Callers/Strip' and st.name='JD' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 3, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-07' and ss.part='single' and r.name='Callers/Strip' and st.name='Ruthie' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-07' and ss.part='single' and r.name='Flash Runners' and st.name='Ethan' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 1, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-07' and ss.part='single' and r.name='Flash Runners' and st.name='Gaby' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 2, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-07' and ss.part='single' and r.name='Flash Runners' and st.name='Sarah' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 3, true, false, 'Nathan*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-07' and ss.part='single' and r.name='Flash Runners' and st.name='Nathan' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 4, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-07' and ss.part='single' and r.name='Flash Runners' and st.name='Cindy' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 5, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-07' and ss.part='single' and r.name='Flash Runners' and st.name='James G.' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 6, true, false, 'Thao*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-07' and ss.part='single' and r.name='Flash Runners' and st.name='Thao' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 7, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-07' and ss.part='single' and r.name='Flash Runners' and st.name='Malaya' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 8, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-07' and ss.part='single' and r.name='Flash Runners' and st.name='Nate' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 9, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-07' and ss.part='single' and r.name='Flash Runners' and st.name='Michael S.' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 10, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-07' and ss.part='single' and r.name='Flash Runners' and st.name='Claudia' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='AM' and r.name='MOD' and st.name='Sagit' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='AM' and r.name='Opener/Swing Shift' and st.name='Sagit' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='AM' and r.name='Paymaster' and st.name='Paolo' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='AM' and r.name='Flash Manager' and st.name='Wayne' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='AM' and r.name='Callers/Strip' and st.name='Tatiana' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 1, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='AM' and r.name='Callers/Strip' and st.name='Esther' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 2, true, false, 'Nathan*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='AM' and r.name='Callers/Strip' and st.name='Nathan' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 3, true, false, 'Raman*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='AM' and r.name='Callers/Strip' and st.name='Raman' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='AM' and r.name='Flash Runners' and st.name='Tiffany' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 1, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='AM' and r.name='Flash Runners' and st.name='Hector' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 2, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='AM' and r.name='Flash Runners' and st.name='Tibet' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 3, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='AM' and r.name='Flash Runners' and st.name='Michael L.' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 4, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='AM' and r.name='Flash Runners' and st.name='Cindy' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 5, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='AM' and r.name='Flash Runners' and st.name='James G.' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 6, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='AM' and r.name='Flash Runners' and st.name='Sarah' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 7, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='AM' and r.name='Flash Runners' and st.name='Thao' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 8, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='AM' and r.name='Flash Runners' and st.name='Nate' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 9, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='AM' and r.name='Flash Runners' and st.name='Amanda' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 10, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='AM' and r.name='Flash Runners' and st.name='Katie' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 11, true, false, 'Sammy*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='AM' and r.name='Flash Runners' and st.name='Sammy' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='PM' and r.name='MOD' and st.name='Sagit' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='PM' and r.name='Opener/Swing Shift' and st.name='Sammy' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='PM' and r.name='Paymaster' and st.name='Paolo' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='PM' and r.name='Flash Manager' and st.name='Esther' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='PM' and r.name='Callers/Strip' and st.name='JD' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 1, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='PM' and r.name='Callers/Strip' and st.name='James C.' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 2, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='PM' and r.name='Callers/Strip' and st.name='Nathan' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 3, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='PM' and r.name='Callers/Strip' and st.name='Raman' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='PM' and r.name='Flash Runners' and st.name='Osbaldo' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 1, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='PM' and r.name='Flash Runners' and st.name='Hector' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 2, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='PM' and r.name='Flash Runners' and st.name='Tibet' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 3, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='PM' and r.name='Flash Runners' and st.name='Sergiy' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 4, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='PM' and r.name='Flash Runners' and st.name='Alex' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 5, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='PM' and r.name='Flash Runners' and st.name='Claudia' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 6, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='PM' and r.name='Flash Runners' and st.name='Thao' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 7, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='PM' and r.name='Flash Runners' and st.name='Iraina' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 8, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-08' and ss.part='PM' and r.name='Flash Runners' and st.name='Michael S.' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='AM' and r.name='MOD' and st.name='Gina' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='AM' and r.name='Opener/Swing Shift' and st.name='Gina' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='AM' and r.name='Paymaster' and st.name='James C.' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='AM' and r.name='Flash Manager' and st.name='Paolo' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, true, false, 'Wayne*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='AM' and r.name='Callers/Strip' and st.name='Wayne' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 1, true, false, 'Cody*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='AM' and r.name='Callers/Strip' and st.name='Cody' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 2, true, false, 'JD*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='AM' and r.name='Callers/Strip' and st.name='JD' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 3, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='AM' and r.name='Callers/Strip' and st.name='Raman' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='AM' and r.name='Flash Runners' and st.name='Tiffany' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 1, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='AM' and r.name='Flash Runners' and st.name='Hector' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 2, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='AM' and r.name='Flash Runners' and st.name='Justin' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 3, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='AM' and r.name='Flash Runners' and st.name='Michael L.' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 4, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='AM' and r.name='Flash Runners' and st.name='Jordy' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 5, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='AM' and r.name='Flash Runners' and st.name='James G.' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 6, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='AM' and r.name='Flash Runners' and st.name='Claudia' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 7, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='AM' and r.name='Flash Runners' and st.name='Malaya' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 8, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='AM' and r.name='Flash Runners' and st.name='Andrea' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 9, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='AM' and r.name='Flash Runners' and st.name='Amanda' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 10, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='AM' and r.name='Flash Runners' and st.name='Katie' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='PM' and r.name='MOD' and st.name='Gina' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='PM' and r.name='Opener/Swing Shift' and st.name='Raman' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='PM' and r.name='Paymaster' and st.name='Wayne' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='PM' and r.name='Flash Manager' and st.name='Esther' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='PM' and r.name='Callers/Strip' and st.name='JD' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 1, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='PM' and r.name='Callers/Strip' and st.name='Cody' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 2, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='PM' and r.name='Callers/Strip' and st.name='James C.' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 3, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='PM' and r.name='Callers/Strip' and st.name='Paula' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='PM' and r.name='Flash Runners' and st.name='Osbaldo' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 1, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='PM' and r.name='Flash Runners' and st.name='Hector' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 2, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='PM' and r.name='Flash Runners' and st.name='Iraina' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 3, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='PM' and r.name='Flash Runners' and st.name='Sergiy' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 4, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='PM' and r.name='Flash Runners' and st.name='Ethan' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 5, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='PM' and r.name='Flash Runners' and st.name='Cameron' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 6, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='PM' and r.name='Flash Runners' and st.name='Claudia' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 7, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='PM' and r.name='Flash Runners' and st.name='Malaya' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 8, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='PM' and r.name='Flash Runners' and st.name='Nate' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 9, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='PM' and r.name='Flash Runners' and st.name='Michael S.' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 10, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-09' and ss.part='PM' and r.name='Flash Runners' and st.name='Dante' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-10' and ss.part='single' and r.name='MOD' and st.name='Sagit' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-10' and ss.part='single' and r.name='Opener/Swing Shift' and st.name='Wayne' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-10' and ss.part='single' and r.name='Paymaster' and st.name='Sagit' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-10' and ss.part='single' and r.name='Flash Manager' and st.name='Paolo' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-10' and ss.part='single' and r.name='Callers/Strip' and st.name='Gina' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 1, true, false, 'Cody*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-10' and ss.part='single' and r.name='Callers/Strip' and st.name='Cody' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 2, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-10' and ss.part='single' and r.name='Callers/Strip' and st.name='James C.' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 3, true, false, 'Ruthie/Raman*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-10' and ss.part='single' and r.name='Callers/Strip' and st.name='Ruthie' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 0, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-10' and ss.part='single' and r.name='Flash Runners' and st.name='Esteban' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 1, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-10' and ss.part='single' and r.name='Flash Runners' and st.name='Hector' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 2, true, false, 'Virginia*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-10' and ss.part='single' and r.name='Flash Runners' and st.name='Virginia' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 3, true, false, 'Nathan*', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-10' and ss.part='single' and r.name='Flash Runners' and st.name='Nathan' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 4, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-10' and ss.part='single' and r.name='Flash Runners' and st.name='Tim' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 5, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-10' and ss.part='single' and r.name='Flash Runners' and st.name='James G.' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 6, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-10' and ss.part='single' and r.name='Flash Runners' and st.name='Claudia' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 7, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-10' and ss.part='single' and r.name='Flash Runners' and st.name='Malaya' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 8, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-10' and ss.part='single' and r.name='Flash Runners' and st.name='Andrea' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 9, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-10' and ss.part='single' and r.name='Flash Runners' and st.name='Michael S.' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 10, false, false, null, 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-10' and ss.part='single' and r.name='Flash Runners' and st.name='Dante' on conflict (session_id, role_id, slot_index) do nothing;
insert into sched_assignments (session_id, role_id, staff_id, slot_index, early_start, is_training, note, response) select ss.id, r.id, st.id, 11, true, true, 'Thao-Training *', 'accepted' from sched_sessions ss, sched_roles r, sched_staff st where ss.hall_id='sc' and ss.session_date='2026-08-10' and ss.part='single' and r.name='Flash Runners' and st.name='Thao' on conflict (session_id, role_id, slot_index) do nothing;
commit;
